name: Update file from lib3mf

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Download release asset
      run: |
        curl -s https://api.github.com/repos/3MFConsortium/lib3mf/releases/tags/v2.2.0 \
        | grep "browser_download_url.*zip" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -qi -

    - name: Unzip release asset
      run: unzip "lib3mf_sdk_v2.2.0.zip"

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Bindings/Python/Lib3MF.py
        git add Bin/*
        git commit -m "Update files from lib3mf release" -a
        git push
